http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/api/*'
  chat:
    host: localhost
    paths: '/chat/*'
  web:
    host: localhost
    paths: '/web/*'
serviceEndpoints:
  chatServer:
    url: 'http://localhost:3000'
  webServer:
    url: 'http://localhost:4000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - auth
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - cors:
          - action:
              origin: '*'
              credentials: true
      - auth:
      - jwt:
          - action:
              secretOrPublicKey: 'e9d4bbb21e0f9d5426d7856fa0d4716de2fed982'
              checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: webServer
              changeOrigin: true
  chatPipeline:
    apiEndpoints:
      - chat
    policies:
      - cors:
          - action:
              origin: '*'
              credentials: true
      - auth:
      - jwt:
          - action:
              secretOrPublicKey: 'your_jwt_secret'
              checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: chatServer
              changeOrigin: true
  webPipeline:
    apiEndpoints:
      - web
    policies:
      - cors:
          - action:
              origin: '*'
              credentials: true
      - auth:
      - jwt:
          - action:
              secretOrPublicKey: 'your_jwt_secret'
              checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: webServer
              changeOrigin: true