http:
  port: 8080

apiEndpoints:
  auth:
    host: '*'
    paths: '/auth/*'
  web:
    host: '*'
    paths: '/web/*'
  chat:
    host: '*'
    paths: '/chat/*'

serviceEndpoints:
  backendService:
    url: 'http://localhost:3001'
  chatService:
    url: 'http://localhost:3002'

policies:
  - custom-auth:
  - jwt:
  - proxy:

pipelines:
  # Pipeline for handling authentication
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - custom-auth:
          secretOrPrivateKey: ${JWT_SECRET}

  # Pipeline for protecting web endpoints
  webPipeline:
    apiEndpoints:
      - web
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              userProperty: 'user'
      - proxy:
          - action:
              serviceEndpoint: backendService
              changeOrigin: true

  # Pipeline for protecting chat endpoints
  chatPipeline:
    apiEndpoints:
      - chat
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              userProperty: 'user'
      - proxy:
          - action:
              serviceEndpoint: chatService
              changeOrigin: true
